"""Auto-generated migration

Revision ID: 657b59aaec53
Revises: 87341c8728a7
Create Date: 2024-10-13 10:52:03.029650+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector

# revision identifiers, used by Alembic.
revision: str = '657b59aaec53'
down_revision: Union[str, None] = '87341c8728a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('document_tags_document_id_fkey', 'document_tags', type_='foreignkey')
    op.drop_constraint('document_tags_tag_id_fkey', 'document_tags', type_='foreignkey')
    op.create_foreign_key(None, 'document_tags', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'document_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_group_tags_user_group_id_fkey', 'user_group_tags', type_='foreignkey')
    op.drop_constraint('user_group_tags_tag_id_fkey', 'user_group_tags', type_='foreignkey')
    op.create_foreign_key(None, 'user_group_tags', 'user_groups', ['user_group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_group_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_group_tags', type_='foreignkey')
    op.drop_constraint(None, 'user_group_tags', type_='foreignkey')
    op.create_foreign_key('user_group_tags_tag_id_fkey', 'user_group_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key('user_group_tags_user_group_id_fkey', 'user_group_tags', 'user_groups', ['user_group_id'], ['id'])
    op.drop_constraint(None, 'document_tags', type_='foreignkey')
    op.drop_constraint(None, 'document_tags', type_='foreignkey')
    op.create_foreign_key('document_tags_tag_id_fkey', 'document_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key('document_tags_document_id_fkey', 'document_tags', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###
