"""Auto-generated migration

Revision ID: 62fcf38d2384
Revises: afa68d28ed36
Create Date: 2024-10-12 21:01:17.762681+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector

# revision identifiers, used by Alembic.
revision: str = '62fcf38d2384'
down_revision: Union[str, None] = 'afa68d28ed36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_group_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_group_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
