"""add user email

Revision ID: e250e7676d11
Revises: 8de21dbe81e1
Create Date: 2024-10-09 09:59:16.019132+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector

# revision identifiers, used by Alembic.
revision: str = 'e250e7676d11'
down_revision: Union[str, None] = '8de21dbe81e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('description_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    op.drop_column('documents', 'description_vector')
    # ### end Alembic commands ###
