"""Auto-generated migration

Revision ID: b75bdcac0bfc
Revises: 62fcf38d2384
Create Date: 2024-10-12 21:42:30.996196+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector

# revision identifiers, used by Alembic.
revision: str = 'b75bdcac0bfc'
down_revision: Union[str, None] = '62fcf38d2384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_group_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_group_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
