"""Auto-generated migration

Revision ID: a1a47ed8857a
Revises: c31457552bde
Create Date: 2024-10-13 23:06:17.475626+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector

# revision identifiers, used by Alembic.
revision: str = 'a1a47ed8857a'
down_revision: Union[str, None] = 'c31457552bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_contents', sa.Column('file_extension', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_contents', 'file_extension')
    # ### end Alembic commands ###
