"""Auto-generated migration

Revision ID: 1c613cc00f31
Revises: 4a33055074fc
Create Date: 2024-10-13 14:18:24.555527+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector

# revision identifiers, used by Alembic.
revision: str = '1c613cc00f31'
down_revision: Union[str, None] = '4a33055074fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'notify',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tags', 'notification_days_before_expiry',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tags', 'notification_frequency',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'notification_frequency',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tags', 'notification_days_before_expiry',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tags', 'notify',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
